/**
 * The wordmark, printed on boot.
 *
 * Generated by scripts/wordmark.py - do not hand-edit.
 *
 * Classic figlet "standard" ASCII art, uppercase, with one blank column between
 * letters so neighbouring stems don't collide.
 *
 * Plain printable ASCII only, so every glyph sits on the same advance in any
 * monospace face and the character grid stays true.
 *
 * These letterforms are held together by | stems running down consecutive rows,
 * so `.row.art` must keep `line-height: 1`. Any extra leading breaks every stem
 * into dashes and the name stops reading.
 */
export const WORDMARK: string[] = [
  "    _         _      _  __     _      ____    _   _      ____    _   _      _      _   _",
  "   / \\       / \\    | |/ /    / \\    / ___|  | | | |    / ___|  | | | |    / \\    | | | |",
  "  / _ \\     / _ \\   | ' /    / _ \\   \\___ \\  | |_| |    \\___ \\  | |_| |   / _ \\   | |_| |",
  " / ___ \\   / ___ \\  | . \\   / ___ \\   ___) | |  _  |     ___) | |  _  |  / ___ \\  |  _  |",
  "/_/   \\_\\ /_/   \\_\\ |_|\\_\\ /_/   \\_\\ |____/  |_| |_|    |____/  |_| |_| /_/   \\_\\ |_| |_|",
];

/** Widest row. The art scales down to keep this many columns on screen. */
export const WORDMARK_COLS = 89;
