/**
 * The wordmark, printed on boot.
 *
 * Generated by scripts/wordmark.py - do not hand-edit.
 *
 * The letters are a 5x7 bitmap font packed two pixel rows per line using the
 * half blocks U+2580/U+2584/U+2588, so a 7px-tall face fits in 4 terminal
 * rows at a roughly square pixel. Those glyphs sit on exactly the same advance
 * as a space in this site's font stack, so the character grid stays true.
 *
 * They only read as solid strokes while `.row.art` keeps `line-height: 1`.
 * A full block's ink spans 1.17em, so any larger line-height opens a seam
 * straight through every stroke.
 */
export const WORDMARK: string[] = [
  "▄▀▀▀▄ ▄▀▀▀▄ █  ▄▀ ▄▀▀▀▄ ▄▀▀▀▀ █   █    ▄▀▀▀▀ █   █ ▄▀▀▀▄ █   █",
  "█▄▄▄█ █▄▄▄█ █▄▀   █▄▄▄█ ▀▄▄▄  █▄▄▄█    ▀▄▄▄  █▄▄▄█ █▄▄▄█ █▄▄▄█",
  "█   █ █   █ █ ▀▄  █   █     █ █   █        █ █   █ █   █ █   █",
  "▀   ▀ ▀   ▀ ▀   ▀ ▀   ▀ ▀▀▀▀  ▀   ▀    ▀▀▀▀  ▀   ▀ ▀   ▀ ▀   ▀",
];

/** Widest row. The art scales down to keep this many columns on screen. */
export const WORDMARK_COLS = 62;
