"""
Regenerates src/lib/ascii.ts, the wordmark printed on boot.

    python scripts/wordmark.py

The letters are the classic figlet "standard" face - the ASCII art every
terminal banner is drawn in, built from _ / \\ | and (). Two details keep it
readable, and both were wrong in an earlier version:

  * One blank column between letters. Without it neighbouring stems collide and
    the whole thing reads as texture rather than as a name.
  * `.row.art` must keep `line-height: 1`. These letterforms are held together
    by | stems running down consecutive rows; any extra leading breaks every
    stem into dashes. See the note in src/styles/terminal.css.

Uppercase, because at this size lowercase has barely two rows of x-height and
turns to mush.

To change the name, edit NAME and add any missing letters to FONT.
"""
import json
import pathlib

NAME = 'AAKASH SHAH'
GAP = 1  # blank columns between letters

FONT = {
    'A': [
        '    _    ',
        '   / \\   ',
        '  / _ \\  ',
        ' / ___ \\ ',
        '/_/   \\_\\',
    ],
    'H': [
        ' _   _ ',
        '| | | |',
        '| |_| |',
        '|  _  |',
        '|_| |_|',
    ],
    'K': [
        ' _  __',
        '| |/ /',
        "| ' / ",
        '| . \\ ',
        '|_|\\_\\',
    ],
    'S': [
        ' ____  ',
        '/ ___| ',
        '\\___ \\ ',
        ' ___) |',
        '|____/ ',
    ],
    ' ': ['  '] * 5,
}

HEADER = '''/**
 * The wordmark, printed on boot.
 *
 * Generated by scripts/wordmark.py - do not hand-edit.
 *
 * Classic figlet "standard" ASCII art, uppercase, with one blank column between
 * letters so neighbouring stems don't collide.
 *
 * Plain printable ASCII only, so every glyph sits on the same advance in any
 * monospace face and the character grid stays true.
 *
 * These letterforms are held together by | stems running down consecutive rows,
 * so `.row.art` must keep `line-height: 1`. Any extra leading breaks every stem
 * into dashes and the name stops reading.
 */
'''


def render(text: str, gap: int = GAP) -> list[str]:
    missing = sorted({c for c in text if c not in FONT})
    if missing:
        raise SystemExit(f'no glyph for: {missing!r} - add it to FONT')
    height = len(FONT['A'])
    rows = [''] * height
    for i, ch in enumerate(text):
        g = FONT[ch]
        w = max(len(r) for r in g)
        for r in range(height):
            rows[r] += g[r].ljust(w)
            if i != len(text) - 1:
                rows[r] += ' ' * gap
    return [r.rstrip() for r in rows]


def main() -> None:
    art = render(NAME)
    cols = max(len(r) for r in art)
    out = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'lib' / 'ascii.ts'
    body = ',\n'.join('  ' + json.dumps(r) for r in art)
    out.write_text(
        HEADER
        + 'export const WORDMARK: string[] = [\n'
        + f'{body},\n'
        + '];\n\n'
        + '/** Widest row. The art scales down to keep this many columns on screen. */\n'
        + f'export const WORDMARK_COLS = {cols};\n',
        encoding='utf-8',
    )
    for r in art:
        print(r)
    print(f'\nwrote {out}  ({len(art)} rows x {cols} cols)')


if __name__ == '__main__':
    main()
