"""
Regenerates src/lib/ascii.ts, the wordmark printed on boot.

    python scripts/wordmark.py

The letters are a 5x7 bitmap font. Rendering packs two pixel rows into each text
row using the half blocks U+2580/U+2584/U+2588, which is what fits a legible
face into four terminal rows at a roughly square pixel.

Those glyphs sit on the same advance as a space in the site's font stack, so the
character grid stays true. They only read as solid strokes while `.row.art`
keeps `line-height: 1` - see the note in src/styles/terminal.css.

To change the name, edit NAME below and add any missing letters to FONT.
"""
import json
import pathlib

NAME = 'AAKASH SHAH'
GAP = 1  # blank pixel columns between letters

# 5 wide x 7 tall.
FONT = {
    'A': [
        '.###.',
        '#...#',
        '#...#',
        '#####',
        '#...#',
        '#...#',
        '#...#',
    ],
    'H': [
        '#...#',
        '#...#',
        '#...#',
        '#####',
        '#...#',
        '#...#',
        '#...#',
    ],
    'K': [
        '#...#',
        '#..#.',
        '#.#..',
        '##...',
        '#.#..',
        '#..#.',
        '#...#',
    ],
    'S': [
        '.####',
        '#....',
        '#....',
        '.###.',
        '....#',
        '....#',
        '####.',
    ],
    ' ': ['..'] * 7,
}

HALF = {(True, True): '\u2588', (True, False): '\u2580',
        (False, True): '\u2584', (False, False): ' '}

HEADER = '''/**
 * The wordmark, printed on boot.
 *
 * Generated by scripts/wordmark.py - do not hand-edit.
 *
 * The letters are a 5x7 bitmap font packed two pixel rows per line using the
 * half blocks U+2580/U+2584/U+2588, so a 7px-tall face fits in {rows} terminal
 * rows at a roughly square pixel. Those glyphs sit on exactly the same advance
 * as a space in this site's font stack, so the character grid stays true.
 *
 * They only read as solid strokes while `.row.art` keeps `line-height: 1`.
 * A full block's ink spans 1.17em, so any larger line-height opens a seam
 * straight through every stroke.
 */
'''


def bitmap(text: str, gap: int = GAP) -> list[str]:
    """Lay the glyphs out side by side into one pixel grid."""
    missing = sorted({c for c in text if c not in FONT})
    if missing:
        raise SystemExit(f'no glyph for: {missing!r} - add it to FONT')
    height = len(next(iter(FONT.values())))
    rows = [''] * height
    for i, ch in enumerate(text):
        for r in range(height):
            rows[r] += FONT[ch][r]
            if i != len(text) - 1:
                rows[r] += '.' * gap
    return rows


def as_half(rows: list[str]) -> list[str]:
    """Two pixel rows per text row, using upper and lower half blocks."""
    pad = rows + ['.' * len(rows[0])] * (-len(rows) % 2)
    return [
        ''.join(
            HALF[(pad[r][c] == '#', pad[r + 1][c] == '#')]
            for c in range(len(pad[r]))
        ).rstrip()
        for r in range(0, len(pad), 2)
    ]


def main() -> None:
    art = as_half(bitmap(NAME))
    cols = max(len(r) for r in art)
    out = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'lib' / 'ascii.ts'
    body = ',\n'.join('  ' + json.dumps(r, ensure_ascii=False) for r in art)
    out.write_text(
        HEADER.format(rows=len(art))
        + 'export const WORDMARK: string[] = [\n'
        + f'{body},\n'
        + '];\n\n'
        + '/** Widest row. The art scales down to keep this many columns on screen. */\n'
        + f'export const WORDMARK_COLS = {cols};\n',
        encoding='utf-8',
    )
    for r in art:
        print(r)
    print(f'\nwrote {out}  ({len(art)} rows x {cols} cols)')


if __name__ == '__main__':
    main()
